### ISSUE TITLE
Alterar nome do repositório.

### ISSUE THREAD

**Issue by lanamesquita** [equipe-GEP/equipe-GEP.github.io#17]
Oi gente, pra que o repositório seja reconhecido como uma página git.io é necessário ter o mesmo nome da organização. Vejam: pratica-03.github.io

Vejam exemplo: https://github.com/UFC-GC-2020-2/UFC-GC-2020-2.github.io
https://ufc-gc-2020-2.github.io/

**Comment by ericrodriguesfer** [comment]
Obrigado pela observação professora, esses ajustes foram feitos e o deploy está funcionando corretamente!
Muito obrigado :)
